const exporterSource = `(async()=>{try{
const normalize=(value)=>(value||'').trim().replace(/\\s+/g,' ').normalize('NFKC');
if(location.hostname!=='www.jrepoint.jp'||!location.pathname.startsWith('/member/pointlog')){alert('JRE POINTのポイント履歴画面で実行してください。');return;}
const numberFrom=(value)=>{const match=normalize(value).replace(/,/g,'').match(/[+-]?\\d+/);return match?Number(match[0]):null;};
const isoDate=(value)=>{const match=normalize(value).match(/(20\\d{2})年(\\d{1,2})月(\\d{1,2})日/);if(!match)return null;return match[1]+'-'+match[2].padStart(2,'0')+'-'+match[3].padStart(2,'0');};
const expiryDate=(value)=>isoDate(value);
const actualDate=(reflectionDate,place,description)=>{if(!reflectionDate||!normalize(place).includes('モバイルSuica')||!normalize(description).includes('チャージ'))return null;const match=normalize(description).match(/(^|\\D)(\\d{1,2})\\/(\\d{1,2})(?=\\D|$)/);if(!match)return null;const reflection=new Date(reflectionDate+'T00:00:00');let year=reflection.getFullYear();const month=Number(match[2]);if(month>reflection.getMonth()+1)year-=1;return year+'-'+String(month).padStart(2,'0')+'-'+String(Number(match[3])).padStart(2,'0');};
const parseRows=(doc)=>Array.from(doc.querySelectorAll('table.pointlogTable tr')).slice(1).map((row)=>{const cells=Array.from(row.querySelectorAll('td')).map((cell)=>normalize(cell.textContent));if(cells.length<5)return null;const reflectionDate=isoDate(cells[1]);const points=numberFrom(cells[4]);if(!reflectionDate||points===null)return null;const place=cells[2];const description=cells[3];const image=row.querySelector('img');return{reflection_date:reflectionDate,actual_date:actualDate(reflectionDate,place,description),place,description,points,source_icon:image?new URL(image.getAttribute('src')||'',location.origin).pathname.split('/').pop()||null:null};}).filter(Boolean);
const rows=[];let doc=document;let pageCount=0;const visited=new Set([location.href]);
for(let index=0;index<13;index+=1){pageCount+=1;rows.push(...parseRows(doc));const previous=doc.querySelector('a.c-link-prev[href*="move=prev"]');if(!previous)break;const url=new URL(previous.getAttribute('href'),location.origin).href;if(visited.has(url))break;visited.add(url);const response=await fetch(url,{credentials:'include'});if(!response.ok)throw new Error('過去履歴を取得できませんでした。');const html=await response.text();const nextDoc=new DOMParser().parseFromString(html,'text/html');if(normalize(nextDoc.querySelector('h1')?.textContent).includes('ログイン')||!nextDoc.querySelector('table.pointlogTable'))throw new Error('認証が切れています。第2パスワード認証後に再実行してください。');doc=nextDoc;}
const total=numberFrom(document.querySelector('.c-header_pointAll')?.textContent);const limited=numberFrom(document.querySelector('.c-header_pointLimit')?.textContent)||0;const nearestExpiry=expiryDate(document.querySelector('.c-header_pointDate')?.textContent);if(total===null)throw new Error('総保有ポイントを取得できませんでした。');
const payload={format:'nkkakeist-jre-point-history',version:1,captured_at:new Date().toISOString(),balance:{total,limited,regular:total-limited,nearest_expiry:nearestExpiry},page_count:pageCount,rows};
const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='jre-point-history-'+new Date().toISOString().slice(0,10).replace(/-/g,'')+'.json';document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);alert(rows.length+'件の履歴と現在残高を書き出しました。');
}catch(error){alert('JRE POINT履歴を書き出せませんでした: '+(error instanceof Error?error.message:String(error)));}})()`;

export const jrePointBookmarklet = `javascript:${encodeURIComponent(exporterSource)}`;
