const exporterSource = `(async()=>{try{
const normalize=(value)=>(value||'').trim().replace(/\\s+/g,' ').normalize('NFKC');
if(location.hostname!=='moneyforward.com'&&!location.hostname.endsWith('.moneyforward.com')){alert('Money Forward MEのWeb版で実行してください。');return;}
const amountFrom=(value)=>{const match=normalize(value).replace(/,/g,'').match(/-?\\d+(?:\\.\\d+)?(?=円)/);return match?Number(match[0]):null;};
const decimalFrom=(value)=>{const match=normalize(value).replace(/,/g,'').match(/[+-]?\\d+(?:\\.\\d+)?/);return match?match[0]:null;};
const localDate=(date)=>date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0');
const fetchDocument=async(path)=>{if(location.pathname===path)return document;const response=await fetch(path,{credentials:'include'});if(!response.ok)throw new Error(path+'を取得できませんでした。');const html=await response.text();const doc=new DOMParser().parseFromString(html,'text/html');if(doc.querySelector('input[type="password"]')||normalize(doc.querySelector('h1')?.textContent).includes('ログイン'))throw new Error('認証が切れています。Money Forwardへログインし直してください。');return doc;};
const headerTexts=(table)=>Array.from(table.querySelectorAll('thead th')).map((cell)=>normalize(cell.textContent));
const directCells=(row)=>Array.from(row.children).filter((cell)=>cell.tagName==='TD');
const investmentAccountName=(institution)=>institution.includes('THEO')?'THEO':institution.includes('ソニー銀行')?'ソニー銀行 投資信託':institution;
const pensionSourceName='Money Forward 年金';
const isBankInstitution=(institution)=>/(銀行|信用金庫|信用組合|労働金庫|農業協同組合|JAバンク)/.test(institution);
const grouped=new Map();
const add=(name,kind,amount,detail,position=null)=>{if(!name||!Number.isFinite(amount)||(kind==='account_balance'?amount===0:amount<=0))return;const key=kind+'|'+name;let item=grouped.get(key);if(!item){item={source_account_name:name,balance_kind:kind,balance:0,currency:'JPY',details:[],positions:[]};grouped.set(key,item);}item.balance+=amount;if(detail)item.details.push(detail);if(position){const existing=item.positions.find((candidate)=>candidate.external_id===position.external_id);if(existing){existing.valuation=String(Number(existing.valuation)+Number(position.valuation));}else{item.positions.push(position);}}};
const portfolio=await fetchDocument('/bs/portfolio');
const assetBreakdown={};let totalAssets=0;
for(const table of portfolio.querySelectorAll('table')){const headers=headerTexts(table);if(!headers.includes('預金・現金')||!headers.includes('投資信託'))continue;for(const row of table.querySelectorAll('tbody tr')){const cells=directCells(row);const label=normalize(cells[0]?.textContent);const amount=amountFrom(cells[1]?.textContent);if(label&&amount!==null&&amount>=0){assetBreakdown[label]=String(amount);totalAssets+=amount;}}break;}
for(const table of portfolio.querySelectorAll('table')){const headers=headerTexts(table);const institutionIndex=headers.indexOf('保有金融機関');const valuationIndex=headers.indexOf('評価額');const instrumentIndex=headers.indexOf('銘柄名');if(institutionIndex<0||valuationIndex<0||instrumentIndex<0)continue;const quantityIndex=headers.indexOf('保有数');const acquisitionPriceIndex=headers.includes('平均取得単価')?headers.indexOf('平均取得単価'):headers.indexOf('取得単価');const unitPriceIndex=headers.includes('基準価額')?headers.indexOf('基準価額'):headers.indexOf('現在値');const gainIndex=headers.indexOf('評価損益');const assetClass=headers.includes('基準価額')?'investment_fund':'security';for(const row of table.querySelectorAll('tbody tr')){const cells=directCells(row);const institution=normalize(cells[institutionIndex]?.textContent);const instrumentName=normalize(cells[instrumentIndex]?.textContent);const amount=amountFrom(cells[valuationIndex]?.textContent);if(!institution||!instrumentName||amount===null)continue;const accountName=investmentAccountName(institution);const unrealizedGain=gainIndex>=0?amountFrom(cells[gainIndex]?.textContent):null;add(accountName,'valuation',amount,instrumentName,{instrument_name:instrumentName,external_id:['money_forward',institution,instrumentName].join(':').slice(0,255),asset_class:assetClass,quantity:quantityIndex>=0?decimalFrom(cells[quantityIndex]?.textContent):null,average_acquisition_price:acquisitionPriceIndex>=0?decimalFrom(cells[acquisitionPriceIndex]?.textContent):null,unit_price:unitPriceIndex>=0?decimalFrom(cells[unitPriceIndex]?.textContent):null,valuation:String(amount),unrealized_gain:unrealizedGain===null?null:String(unrealizedGain),currency:'JPY'});}}
const pensionSection=portfolio.querySelector('#portfolio_det_pns');
if(pensionSection){const pensionHasData=Array.from(pensionSection.querySelectorAll('tbody tr')).some((row)=>directCells(row).some((cell)=>amountFrom(cell.textContent)!==null));let pensionRows=0;for(const table of pensionSection.querySelectorAll('table')){const headers=headerTexts(table);const instrumentIndex=headers.indexOf('名称');const valuationIndex=headers.indexOf('現在価値');if(instrumentIndex<0||valuationIndex<0)continue;const acquisitionCostIndex=headers.indexOf('取得価額');const gainIndex=headers.indexOf('評価損益');for(const row of table.querySelectorAll('tbody tr')){const cells=directCells(row);const instrumentName=normalize(cells[instrumentIndex]?.textContent);const amount=amountFrom(cells[valuationIndex]?.textContent);if(!instrumentName||amount===null)continue;const acquisitionCost=acquisitionCostIndex>=0?amountFrom(cells[acquisitionCostIndex]?.textContent):null;const unrealizedGain=gainIndex>=0?amountFrom(cells[gainIndex]?.textContent):null;add(pensionSourceName,'valuation',amount,instrumentName,{instrument_name:instrumentName,external_id:['money_forward','pension',instrumentName].join(':').slice(0,255),asset_class:'defined_contribution_pension',acquisition_cost:acquisitionCost===null?null:String(acquisitionCost),quantity:null,average_acquisition_price:null,unit_price:null,valuation:String(amount),unrealized_gain:unrealizedGain===null?null:String(unrealizedGain),currency:'JPY'});pensionRows++;}}if(pensionHasData&&pensionRows===0)throw new Error('年金の銘柄明細形式を認識できませんでした。Money Forwardの画面構造が変わっていないか確認してください。');}
for(const table of portfolio.querySelectorAll('table')){const headers=headerTexts(table);const assetNameIndex=headers.indexOf('種類・名称');const balanceIndex=headers.indexOf('残高');const institutionIndex=headers.indexOf('保有金融機関');if(assetNameIndex<0||balanceIndex<0||institutionIndex<0||!table.closest('#portfolio_det_depo'))continue;for(const row of table.querySelectorAll('tbody tr')){const cells=directCells(row);const assetName=normalize(cells[assetNameIndex]?.textContent);const institution=normalize(cells[institutionIndex]?.textContent);const amount=amountFrom(cells[balanceIndex]?.textContent);if(amount===null)continue;if(institution.includes('THEO'))add('THEO','valuation',amount,assetName);else if(isBankInstitution(institution))add(institution,'account_balance',amount,assetName);}}
const liability=await fetchDocument('/bs/liability');
for(const table of liability.querySelectorAll('table')){const headers=headerTexts(table);const typeIndex=headers.indexOf('種類');const balanceIndex=headers.indexOf('残高');const institutionIndex=headers.indexOf('保有金融機関');if(typeIndex<0||balanceIndex<0||institutionIndex<0)continue;for(const row of table.querySelectorAll('tbody tr')){const cells=directCells(row);const type=normalize(cells[typeIndex]?.textContent);if(!type.includes('クレジットカード'))continue;const institution=normalize(cells[institutionIndex]?.textContent);const amount=amountFrom(cells[balanceIndex]?.textContent);if(amount!==null)add(institution,'card_outstanding',Math.abs(amount),'ご利用残高');}}
const capturedAt=new Date();const balanceDate=localDate(capturedAt);const items=Array.from(grouped.values()).map((item)=>({source_account_name:item.source_account_name,balance_kind:item.balance_kind,balance:String(item.balance),currency:item.currency,balance_date:balanceDate,external_id:['money_forward',item.balance_kind,item.source_account_name,balanceDate].join(':'),source_details:item.details,...(item.positions.length>0?{positions:item.positions}:{})}));
if(items.length===0)throw new Error('対象となる銀行預金・投資信託・年金・カード利用残高が見つかりませんでした。');
const summary=items.map((item)=>'・'+item.source_account_name+' '+Number(item.balance).toLocaleString()+'円'+(item.positions?'（'+item.positions.length+'銘柄）':'')).join('\\n');if(!confirm('次の残高をJSONへ書き出します。\\n\\n'+summary+'\\n\\nNKKakeistのプレビューで口座対応を確認してください。'))return;
const assetHistory=totalAssets>0?{captured_on:balanceDate,total_assets:String(totalAssets),currency:'JPY',breakdown:assetBreakdown}:null;
const payload={format:'nkkakeist-balance-snapshot',version:1,source:'money_forward',captured_at:capturedAt.toISOString(),items,...(assetHistory?{asset_history:assetHistory}:{})};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='money-forward-balances-'+balanceDate.replace(/-/g,'')+'.json';document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);alert(items.length+'口座の公式残高・評価額と総資産サマリーを書き出しました。');
}catch(error){alert('Money Forward残高を書き出せませんでした: '+(error instanceof Error?error.message:String(error)));}})()`;

export const moneyForwardBalanceBookmarklet = `javascript:${encodeURIComponent(exporterSource)}`;
