const exporterSource = `(async()=>{try{
const normalize=(value)=>(value||'').trim().replace(/\\s+/g,' ').normalize('NFKC');
if(location.hostname!=='moneyforward.com'&&!location.hostname.endsWith('.moneyforward.com')){alert('Money Forward MEのWeb版で実行してください。');return;}
const amountFrom=(value)=>{const match=normalize(value).replace(/,/g,'').match(/-?\\d+(?:\\.\\d+)?(?=円)/);return match?Number(match[0]):null;};
const decimalFrom=(value)=>{const match=normalize(value).replace(/,/g,'').match(/[+-]?\\d+(?:\\.\\d+)?/);return match?match[0]:null;};
const localDate=(date)=>date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0');
const fetchDocument=async(path)=>{if(location.pathname===path)return document;const response=await fetch(path,{credentials:'include'});if(!response.ok)throw new Error(path+'を取得できませんでした。');const html=await response.text();const doc=new DOMParser().parseFromString(html,'text/html');if(doc.querySelector('input[type="password"]')||normalize(doc.querySelector('h1')?.textContent).includes('ログイン'))throw new Error('認証が切れています。Money Forwardへログインし直してください。');return doc;};
const diagnostics={exporter_version:2,portfolio_summary_table:false,investment_tables:0,deposit_table:false,pension_table:false,liability_tables:0};
const headerTexts=(table)=>Array.from(table.querySelectorAll('thead th')).map((cell)=>normalize(cell.textContent));
const directCells=(row)=>Array.from(row.children).filter((cell)=>cell.tagName==='TD');
const investmentAccountName=(institution)=>institution.includes('THEO')?'THEO':institution.includes('ソニー銀行')?'ソニー銀行 投資信託':institution;
const pensionSourceName='Money Forward 年金';
const isBankInstitution=(institution)=>/(銀行|信用金庫|信用組合|労働金庫|農業協同組合|JAバンク)/.test(institution);
const grouped=new Map();
const add=(name,kind,amount,detail,position=null)=>{if(!name||!Number.isFinite(amount)||(kind==='account_balance'?amount===0:amount<=0))return;const key=kind+'|'+name;let item=grouped.get(key);if(!item){item={source_account_name:name,balance_kind:kind,balance:0,currency:'JPY',details:[],positions:[]};grouped.set(key,item);}item.balance+=amount;if(detail)item.details.push(detail);if(position){const existing=item.positions.find((candidate)=>candidate.external_id===position.external_id);if(existing){existing.valuation=String(Number(existing.valuation)+Number(position.valuation));for(const field of ['acquisition_cost','unrealized_gain']){if(existing[field]!==null&&position[field]!==null)existing[field]=String(Number(existing[field])+Number(position[field]));else if(existing[field]===null)existing[field]=position[field];}}else{item.positions.push(position);}}};
const portfolio=await fetchDocument('/bs/portfolio');
let assetBreakdown={};let totalAssets=0;
const isAssetCategory=(label)=>/^(預金・現金|株式(?:\([^)]*\))?|投資信託|債券|年金|ポイント|不動産|保険|その他(?:の資産)?|FX|暗号資産|コモディティ)$/.test(label);
for(const table of portfolio.querySelectorAll('table')){const candidate={};for(const row of table.querySelectorAll('tbody tr')){const cells=Array.from(row.children).filter((cell)=>cell.tagName==='TH'||cell.tagName==='TD');const label=normalize(cells[0]?.textContent);if(!isAssetCategory(label))continue;const amount=cells.slice(1).map((cell)=>amountFrom(cell.textContent)).find((value)=>value!==null);if(amount!==undefined&&amount!==null&&amount>=0)candidate[label]=String(amount);}if(Object.keys(candidate).length>Object.keys(assetBreakdown).length)assetBreakdown=candidate;}
if(Object.keys(assetBreakdown).length>0){diagnostics.portfolio_summary_table=true;totalAssets=Object.values(assetBreakdown).reduce((total,amount)=>total+Number(amount),0);}
for(const table of portfolio.querySelectorAll('table')){const headers=headerTexts(table);const institutionIndex=headers.indexOf('保有金融機関');const valuationIndex=headers.indexOf('評価額');const instrumentIndex=headers.indexOf('銘柄名');if(institutionIndex<0||valuationIndex<0||instrumentIndex<0)continue;diagnostics.investment_tables++;const quantityIndex=headers.indexOf('保有数');const acquisitionPriceIndex=headers.includes('平均取得単価')?headers.indexOf('平均取得単価'):headers.indexOf('取得単価');const acquisitionCostIndex=headers.indexOf('取得価額');const unitPriceIndex=headers.includes('基準価額')?headers.indexOf('基準価額'):headers.indexOf('現在値');const gainIndex=headers.indexOf('評価損益');const assetClass=headers.includes('基準価額')?'investment_fund':'security';for(const row of table.querySelectorAll('tbody tr')){const cells=directCells(row);const institution=normalize(cells[institutionIndex]?.textContent);const instrumentName=normalize(cells[instrumentIndex]?.textContent);const amount=amountFrom(cells[valuationIndex]?.textContent);if(!institution||!instrumentName||amount===null)continue;const accountName=investmentAccountName(institution);const unrealizedGain=gainIndex>=0?amountFrom(cells[gainIndex]?.textContent):null;const acquisitionCostFromTable=acquisitionCostIndex>=0?amountFrom(cells[acquisitionCostIndex]?.textContent):null;const acquisitionCost=acquisitionCostFromTable??(unrealizedGain===null?null:amount-unrealizedGain);add(accountName,'valuation',amount,instrumentName,{instrument_name:instrumentName,external_id:['money_forward',institution,instrumentName].join(':').slice(0,255),asset_class:assetClass,quantity:quantityIndex>=0?decimalFrom(cells[quantityIndex]?.textContent):null,average_acquisition_price:acquisitionPriceIndex>=0?decimalFrom(cells[acquisitionPriceIndex]?.textContent):null,unit_price:unitPriceIndex>=0?decimalFrom(cells[unitPriceIndex]?.textContent):null,acquisition_cost:acquisitionCost===null?null:String(acquisitionCost),valuation:String(amount),unrealized_gain:unrealizedGain===null?null:String(unrealizedGain),currency:'JPY'});}}
const investmentSummaryTotal=Object.entries(assetBreakdown).filter(([label])=>/(投資信託|株式|債券|FX|暗号資産)/.test(label)).reduce((total,[,amount])=>total+Number(amount),0);
if(investmentSummaryTotal>0&&diagnostics.investment_tables===0)throw new Error('銘柄別評価額を認識できませんでした。Money Forwardの画面構造が変わった可能性があります。');
const pensionSection=portfolio.querySelector('#portfolio_det_pns');
if(pensionSection){const pensionHasData=Array.from(pensionSection.querySelectorAll('tbody tr')).some((row)=>directCells(row).some((cell)=>amountFrom(cell.textContent)!==null));let pensionRows=0;for(const table of pensionSection.querySelectorAll('table')){const headers=headerTexts(table);const instrumentIndex=headers.indexOf('名称');const valuationIndex=headers.indexOf('現在価値');if(instrumentIndex<0||valuationIndex<0)continue;diagnostics.pension_table=true;const acquisitionCostIndex=headers.indexOf('取得価額');const gainIndex=headers.indexOf('評価損益');for(const row of table.querySelectorAll('tbody tr')){const cells=directCells(row);const instrumentName=normalize(cells[instrumentIndex]?.textContent);const amount=amountFrom(cells[valuationIndex]?.textContent);if(!instrumentName||amount===null)continue;const acquisitionCost=acquisitionCostIndex>=0?amountFrom(cells[acquisitionCostIndex]?.textContent):null;const unrealizedGain=gainIndex>=0?amountFrom(cells[gainIndex]?.textContent):null;add(pensionSourceName,'valuation',amount,instrumentName,{instrument_name:instrumentName,external_id:['money_forward','pension',instrumentName].join(':').slice(0,255),asset_class:'defined_contribution_pension',acquisition_cost:acquisitionCost===null?null:String(acquisitionCost),quantity:null,average_acquisition_price:null,unit_price:null,valuation:String(amount),unrealized_gain:unrealizedGain===null?null:String(unrealizedGain),currency:'JPY'});pensionRows++;}}if(pensionHasData&&pensionRows===0)throw new Error('年金の銘柄明細形式を認識できませんでした。Money Forwardの画面構造が変わっていないか確認してください。');}
const depositSection=portfolio.querySelector('#portfolio_det_depo');const depositHasData=depositSection?Array.from(depositSection.querySelectorAll('tbody tr')).some((row)=>directCells(row).some((cell)=>amountFrom(cell.textContent)!==null)):false;
for(const table of portfolio.querySelectorAll('table')){const headers=headerTexts(table);const assetNameIndex=headers.indexOf('種類・名称');const balanceIndex=headers.indexOf('残高');const institutionIndex=headers.indexOf('保有金融機関');if(assetNameIndex<0||balanceIndex<0||institutionIndex<0||!table.closest('#portfolio_det_depo'))continue;diagnostics.deposit_table=true;for(const row of table.querySelectorAll('tbody tr')){const cells=directCells(row);const assetName=normalize(cells[assetNameIndex]?.textContent);const institution=normalize(cells[institutionIndex]?.textContent);const amount=amountFrom(cells[balanceIndex]?.textContent);if(amount===null)continue;if(institution.includes('THEO'))add('THEO','valuation',amount,assetName);else if(isBankInstitution(institution))add(institution,'account_balance',amount,assetName);}}
if(depositHasData&&!diagnostics.deposit_table)throw new Error('預金・現金明細を認識できませんでした。Money Forwardの画面構造が変わった可能性があります。');
const liability=await fetchDocument('/bs/liability');
const liabilityHasCardText=Array.from(liability.querySelectorAll('tbody tr')).some((row)=>normalize(row.textContent).includes('クレジットカード')&&directCells(row).some((cell)=>amountFrom(cell.textContent)!==null));
for(const table of liability.querySelectorAll('table')){const headers=headerTexts(table);const typeIndex=headers.indexOf('種類');const balanceIndex=headers.indexOf('残高');const institutionIndex=headers.indexOf('保有金融機関');if(typeIndex<0||balanceIndex<0||institutionIndex<0)continue;diagnostics.liability_tables++;for(const row of table.querySelectorAll('tbody tr')){const cells=directCells(row);const type=normalize(cells[typeIndex]?.textContent);if(!type.includes('クレジットカード'))continue;const institution=normalize(cells[institutionIndex]?.textContent);const amount=amountFrom(cells[balanceIndex]?.textContent);if(amount!==null)add(institution,'card_outstanding',Math.abs(amount),'ご利用残高');}}
if(liabilityHasCardText&&diagnostics.liability_tables===0)throw new Error('カード利用残高を認識できませんでした。Money Forwardの画面構造が変わった可能性があります。');
const capturedAt=new Date();const balanceDate=localDate(capturedAt);const items=Array.from(grouped.values()).map((item)=>({source_account_name:item.source_account_name,balance_kind:item.balance_kind,balance:String(item.balance),currency:item.currency,balance_date:balanceDate,external_id:['money_forward',item.balance_kind,item.source_account_name,balanceDate].join(':'),source_details:item.details,...(item.positions.length>0?{positions:item.positions}:{})}));
if(items.length===0)throw new Error('対象となる銀行預金・投資信託・年金・カード利用残高が見つかりませんでした。');
const summary=items.map((item)=>'・'+item.source_account_name+' '+Number(item.balance).toLocaleString()+'円'+(item.positions?'（'+item.positions.length+'銘柄）':'')).join('\\n');if(!confirm('次の残高をJSONへ書き出します。\\n\\n'+summary+'\\n\\nNKKakeistのプレビューで口座対応を確認してください。'))return;
const assetHistory=totalAssets>0?{captured_on:balanceDate,total_assets:String(totalAssets),currency:'JPY',breakdown:assetBreakdown}:null;
const payload={format:'nkkakeist-balance-snapshot',version:1,source:'money_forward',captured_at:capturedAt.toISOString(),diagnostics,items,...(assetHistory?{asset_history:assetHistory}:{})};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='money-forward-balances-'+balanceDate.replace(/-/g,'')+'.json';document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);const checkMessage=diagnostics.portfolio_summary_table?'画面構造チェック: 正常':'画面構造チェック: 一部注意（資産構成表は未認識）';alert(items.length+'口座の公式残高・評価額を書き出しました。'+checkMessage);
}catch(error){alert('Money Forward残高を書き出せませんでした: '+(error instanceof Error?error.message:String(error)));}})()`;

export const moneyForwardBalanceBookmarklet = `javascript:${encodeURIComponent(exporterSource)}`;
